[package]
name = "project-name"
version = "0.1.0"
edition = "2021"

[lib]
name = "project_name"
crate-type = ["cdylib",]


[dependencies]
pyo3 = { version = "^0.24.2", features = ["extension-module"] }
