version: '3'

tasks:
  mise:
    desc: Update mise
    cmds:
      - mise self-update --yes

  tools:
    desc: Update tools
    cmds:
      - mise up --bump

  packages:
    desc: Update packages
    cmds:
      - mise exec -- uv lock --upgrade
      - mise exec -- uv sync
