# This workflow enables Dependabot to automatically rebase dependency updates

name: Review Dependabot PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  review-dependabot-pr:
    uses: diapolo10/.github/.github/workflows/review-dependabot-pr.yml@c8ea0e99f7a5a688ae8f39d4f2163387f231ef1c
    permissions:
      contents: write
      pull-requests: write
      issues: write
